db:
  image: postgres
redis:
  image: redis
  ports:
    - "6379:6379"
worker:
  build: .
  environment:
    - DJANGO_ENV=development_docker
    - DJANGO_SETTINGS_MODULE=settings.development_docker
  command: celery worker --app=apps --workdir=/code/
  volumes:
    - .:/code
  links:
    - db
    - redis
    - web
web:
  build: .
  environment:
    - DJANGO_ENV=development_docker
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - db
    - redis
