version: '3'

services:
  db:
    image: postgres:9.6.2
  redis:
    image: redis:3.2.8
    ports:
      - "6379:6379"
  web:
    build: .
    environment:
      - DJANGO_ENV=development_docker
      - C_FORCE_ROOT=true
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db
      - redis
    stdin_open: true
    tty: true
  worker:
    build: .
    environment:
      - DJANGO_ENV=development_docker
      - DJANGO_SETTINGS_MODULE=settings.development_docker
      - C_FORCE_ROOT=true
    working_dir: /code
    command: celery worker -A apps.core.tasks --loglevel=INFO
    volumes:
      - .:/code
    links:
      - db
      - redis
      - web
